# Generated by Django 6.0.6 on 2026-07-24 05:56

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import reservations.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_booking_currency_booking_price_city_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        default=reservations.models.generate_booking_reference,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("travel_date", models.DateField()),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-travel_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger_bookings",
                to="reservations.reservation",
            ),
        ),
    ]
