# Generated by Django 6.0.6 on 2026-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_reservation_booking_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cabin_class",
            field=models.CharField(
                choices=[("business", "Business"), ("economy", "Economy")],
                default="economy",
                max_length=10,
            ),
        ),
    ]
