# Generated by Django 6.0.6 on 2026-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_booking_unique_seat_booking_per_flight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
